// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABWroEB8UgMgeunHBPXiWCB6UCIk_p4A0',
    appId: '1:771996958308:web:ce3483095bb8389f98a971',
    messagingSenderId: '771996958308',
    projectId: 'news-3d98f',
    authDomain: 'news-3d98f.firebaseapp.com',
    storageBucket: 'news-3d98f.appspot.com',
    measurementId: 'G-5FH3MFYF2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzr8M5VIUPafaaPPgZEUJML_ByWy2Ycp4',
    appId: '1:771996958308:android:d0433360621af97b98a971',
    messagingSenderId: '771996958308',
    projectId: 'news-3d98f',
    storageBucket: 'news-3d98f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3rq89Ul3ywfSVyVzKIlBrsfzO172M1GI',
    appId: '1:771996958308:ios:26adb9f92829f2a598a971',
    messagingSenderId: '771996958308',
    projectId: 'news-3d98f',
    storageBucket: 'news-3d98f.appspot.com',
    iosBundleId: 'com.example.newsAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3rq89Ul3ywfSVyVzKIlBrsfzO172M1GI',
    appId: '1:771996958308:ios:4a40f0c137f6582d98a971',
    messagingSenderId: '771996958308',
    projectId: 'news-3d98f',
    storageBucket: 'news-3d98f.appspot.com',
    iosBundleId: 'com.example.newsAppWithFirebase.RunnerTests',
  );
}
